language: python
install:
  - pip install -r requirements.txt
# command to run tests
# for running your unittests please add the line -python -m unittest unit_tests.py
script:
  - python -m unittest unit_tests.py

